"""Add HRUser

Revision ID: 49fde827afb1
Revises: 556619640823
Create Date: 2026-07-18 02:40:57.356459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fde827afb1'
down_revision: Union[str, Sequence[str], None] = '556619640823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_users_auth_token'), 'hr_users', ['auth_token'], unique=False)
    op.create_index(op.f('ix_hr_users_email'), 'hr_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_users_email'), table_name='hr_users')
    op.drop_index(op.f('ix_hr_users_auth_token'), table_name='hr_users')
    op.drop_table('hr_users')
    # ### end Alembic commands ###
